name: Run test cases
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    name: Test codebase
    environment: Test
    runs-on: ubuntu-latest
    steps:
    - name: Update apt-get
      run: sudo apt-get -q update
    - name: Install latest ca-certificates
      run: sudo apt-get -yq install ca-certificates build-essential
    - name: Setup Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
    - name: Check out source code
      uses: actions/checkout@v1
    - name: Run test cases
      env:
        GOPROXY: "https://proxy.golang.org"
      run: go test -v ./...
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      if: ${{ failure() }}
      env:
        SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
        SLACK_FOOTER: From ${{ github.repository }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_ACTION_REPORT_WEBHOOK }}
